version: '3.7'
services:
  db:
    image: mariadb:10.8.2
    restart: always
    environment:
      MYSQL_DATABASE: dbweb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: Dbuser.1234
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db:/var/lib/mysql
  web:
    image: wordpress:5-php8.1-fpm-alpine
    restart: always
    ports:
      - 81:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: dbuser
      WORDPRESS_DB_PASSWORD: Dbuser.1234
      WORDPRESS_DB_NAME: dbweb
      WORDPRESS_TABLE_PREFIX: web
    depends_on:
      - db
    volumes:
      - ./wordpress:/var/www/html
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 82:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db